version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/dev"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/terraform/prod"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      all:
        patterns:
          - "*"
