web:
  port: 8080

endpoints:
  - name: 96a8b610-7391-45f5-9253-84bee2333669
    group: external
    url: https://reops-event-proxy.ekstern.dev.nav.no/api/send
    headers:
      User-Agent: "Mozilla/5.0 (compatible; reops-monitor/1.0)"
    interval: 1m
    conditions:
      - "[STATUS] == any(200, 201)"
