apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-gatus
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://reops-gatus.ansatt.nav.no
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: reops-event-proxy.ekstern.nav.no
        - application: reops-event-proxy
  env:
    - name: GATUS_LOG_LEVEL
      value: WARN
  replicas:
    min: 1
    max: 1
