name: "Deploy Dev"
run-name: "Deploy Dev - ${{ github.sha }}"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        id: docker-push
        uses: nais/docker-build-push@v0
        with:
          team: team-researchops
      - name: Deploy to NAIS dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}
      - name: Deployment output
        run: |
          echo "Use this image for prod deploys:"
          echo "image=${{ steps.docker-push.outputs.image }}"
